### ISSUE TITLE
1 fps on Intel Integrated Graphics

### ISSUE THREAD

**Issue by ajh123** [tim-oster/voxel-rs#14]
This image says it all:

![image](https://github.com/tim-oster/voxel-rs/assets/41990982/742d3f37-5222-402c-b999-7ef084e6838e)

When using Intel Integrated Graphics I get 1 fps. If I used a proper GPU I assume I will get better FPS?

**Comment by tim-oster** [comment]
Yes, the ray tracer is designed to be executed on GPUs. Integrated graphics don't have enough power to render at interactive frame rates.
